sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shumenov/react-test -f ./client/Dockerfile.dev ./client

  script:
    - docker run -e CI=true shumenov/react-test npm test

  after_success:
    - docker build -t shumenov/multi-client ./client
    - docker build -t shumenov/multi-nginx ./nginx
    - docker build -t shumenov/multi-server ./server
    - docker build -t shumenov/multi-worker ./worker
    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those images and push them to docker hub
    - docker push shumenov/multi-client
    - docker push shumenov/multi-nginx
    - docker push shumenov/multi-server
    - docker push shumenov/multi-worker
