sudo: required
services:
  - docker

  before_install:
    - docker build -t shumenov/react-test -f ./client/Dockerfile.dev

  script:
    - docker run -e CI=true shumenov/react-test npm test -- --coverage

  after_success:
    - docker build -t shumenov/multi-client ./client
    - docker build -t shumenov/multi-nginx ./nginx
    - docker build -t shumenov/multi-server ./server
    - docker build -t shumenov/multi-worker ./worker